## Numpy for Statistical Analysis

In [2]:
import numpy as np

**Create arrays**

In [3]:
# create a 1D numpy array using np.array(list)
lst = [1, 4, 5, 8]
array = np.array(lst, float)
print array

[ 1.  4.  5.  8.]


In [7]:
# create a 2D numpy array
lst_2 = [[1, 2, 3], [4, 5, 6]]
array = np.array(lst_2, float)

In [9]:
# this is a list
# just that it's a list of lists
type(lst_2)

list

**Indexing and slicing**

Numpy follows Python's rules
- Includes the first 
- Excludes the last

In [11]:
# 1D array
array = np.array(lst, float)

In [15]:
array

array([ 1.,  4.,  5.,  8.])

In [17]:
# access second element
array[1]

4.0

In [20]:
# access from first to second
array[: 2]

array([ 1.,  4.])

In [21]:
# access from second to last
array[1:]

array([ 4.,  5.,  8.])

In [22]:
# 2D array
array = np.array(lst_2, float)

In [24]:
array

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [23]:
# row 1, all columns
array[1, :]

array([ 4.,  5.,  6.])

In [27]:
# row 0, column 0 to 1
# as mentioned previously, numpy includes the first, and excludes the last
# so you need to use :2 to reach 1
array[0, :2]

array([ 1.,  2.])